# Bili-Cortex 简化配置文件示例
# 复制此文件为 config.yaml 并修改相应设置

# 核心配置 - 音频和转录
audio:
  quality: 'best'          # 音频质量: best, worst
  format: 'wav'            # 音频格式: wav, mp3, flac

transcription:
  model: 'large-v3'        # 模型大小: tiny, base, small, medium, large, large-v2, large-v3
  language: 'zh-CN'        # 语言代码: zh-CN(简体), zh-TW(繁体), zh(简体), en, ja, ko 等
  device: 'auto'           # 设备: auto, cpu, cuda
  compute_type: 'float16'  # 计算精度: float16, float32, int8

# 系统配置
system:
  log_level: 'INFO'                    # 日志级别: DEBUG, INFO, WARNING, ERROR
  cleanup_temp_files: true            # 是否自动清理临时文件
  data_dir: './data'                  # 数据目录
  temp_dir: './data/temp'             # 临时目录
  transcripts_dir: './data/transcripts' # 转录结果目录

# 知识库配置 - 文本处理和向量化
text_processing:
  chunk_size: 1000         # 文本块大小
  chunk_overlap: 200       # 文本块重叠大小

vectorization:
  model: 'BAAI/bge-large-zh-v1.5'  # 嵌入模型
  device: 'auto'           # 设备: auto, cpu, cuda

# 向量存储
storage:
  db_path: './data/knowledge_base'   # 向量数据库路径
  collection_name: 'bili_videos'     # 集合名称